// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1In2iGPsmji87xP2gcfgA2tgw8CkYYQs',
    appId: '1:390217837576:android:75a499032a3a090ab7b5bd',
    messagingSenderId: '390217837576',
    projectId: 'habit-tracker-7eaa0',
    databaseURL: 'https://habit-tracker-7eaa0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'habit-tracker-7eaa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADlMg3TGOExFkr7bkuMc5mzBR3_cgVOk8',
    appId: '1:390217837576:ios:973eadfa65b91442b7b5bd',
    messagingSenderId: '390217837576',
    projectId: 'habit-tracker-7eaa0',
    databaseURL: 'https://habit-tracker-7eaa0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'habit-tracker-7eaa0.appspot.com',
    androidClientId: '390217837576-4450scethjbaou8b430uco95jcklac92.apps.googleusercontent.com',
    iosClientId: '390217837576-31pji3eggm3ionkrfui8406f5auf5jrj.apps.googleusercontent.com',
    iosBundleId: 'com.thinksys.habitTracker',
  );
}
